USE zomatodb;
SELECT * FROM customer;
SELECT * FROM restaurant;
SELECT * FROM zomato_employee;
SELECT * FROM foods;
SELECT * FROM order_detail;
SELECT * FROM order_food;
SELECT * FROM payment_table;


# 1. List the top 3 customers who have placed the highest number of orders. 
SELECT * FROM customer;
SELECT * FROM order_detail;

SELECT customer_id, COUNT(order_id) AS total_orders
FROM order_detail
GROUP BY customer_id
ORDER BY total_orders DESC
 LIMIT 3; 
 
# 2. Find the restaurant that has received the highest average rating.
SELECT * FROM restaurant;

SELECT restaurant_id , AVG(rrating) 
FROM restaurant
GROUP BY restaurant_id
ORDER BY AVG(rrating)  DESC
LIMIT 1;

#3. List all orders from order_detail that were delivered in under 30 minutes. 
SELECT * FROM order_detail;

SELECT order_id, customer_id, restaurant_id , employee_id , order_status , order_time , delivered_time, 
TIMESTAMPDIFF(MINUTE, order_time , delivered_time) 
FROM  order_detail
WHERE TIMESTAMPDIFF(MINUTE, order_time , delivered_time)  < 30;

# 4. Calculate the total revenue generated by each food item. Display food_id, food_name and Total revenue ordered by total revenue in descending order. 
   SELECT * FROM foods;
   SELECT * FROM order_food;

   SELECT 
   f.food_id , 
   f.food_name , 
   SUM(ofd.quantity * f.price_per_unit) AS `total_revenue` 
   FROM order_food ofd
   JOIN foods f ON ofd.food_id = f.food_id
   GROUP BY f.food_id , f.food_name
   ORDER BY total_revenue DESC;

# 5. Find the second highest revenue-generating restaurant. 
SELECT * FROM restaurant;
SELECT * FROM foods;
SELECT * FROM order_food;

SELECT r.restaurant_id , SUM(f.price_per_unit * o.quantity) AS `total_revenue`
FROM order_food o
JOIN foods f ON o.food_id = f .food_id
JOIN restaurant r ON o.restaurant_id = r.restaurant_id
 GROUP BY r.restaurant_id
 ORDER BY total_revenue DESC
 LIMIT 1 OFFSET 1;
 
 # 6. Find the 5 most popular food items based on the quantity sold. 
 SELECT * FROM foods;
 SELECT * FROM order_food;
 
 SELECT f.food_name , SUM(ofd.quantity) AS `total_quantity_sold`
 FROM order_food ofd
 JOIN foods f ON ofd.food_id = f.food_id
 GROUP BY f.food_name
 ORDER BY total_quantity_sold DESC
 LIMIT 5;
 
 # 7. List the top 3 Zomato employees with the highest average delivery ratings. 
 SELECT * FROM zomato_employee;
 SELECT employee_id , employee_name , employee_avg_rating 
 FROM zomato_employee
 ORDER BY employee_avg_rating DESC
 LIMIT 3;
 
# 8. Determine the month with the highest number of total orders placed. 
SELECT * FROM order_detail;

SELECT 
MONTH(order_time) AS `order_month`,
COUNT(*) AS `total_orders`
FROM order_detail
GROUP BY MONTH(order_time)
ORDER BY total_orders DESC
LIMIT 1; 

# 9. Calculate the average order amount for each customer. Order by average order amount in descending order. 
SELECT * FROM order_detail;
SELECT * FROM order_food;
SELECT * FROM foods;

SELECT 
    od.customer_id,
    AVG(ofd.quantity * f.price_per_unit) AS `avg_order_amount`
FROM order_detail od
JOIN order_food ofd 
    ON od.order_id = ofd.order_id
JOIN foods f 
    ON ofd.food_id = f.food_id
GROUP BY od.customer_id
ORDER BY avg_order_amount DESC;

# 10. Identify the most frequent customer for each restaurant. 

  SELECT * FROM customer;
  SELECT * FROM restaurant;
  SELECT * FROM order_detail;

 SELECT restaurant_id,
       restaurant_name,
       customer_id,
       customer_name,
       total_orders
FROM (
    SELECT r.restaurant_id,
           r.restaurant_name,
           c.customer_id,
           c.customer_name,
           COUNT(od.order_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY r.restaurant_id
               ORDER BY COUNT(od.order_id) DESC
           ) AS rn
    FROM order_detail od
    JOIN customer c 
        ON od.customer_id = c.customer_id
    JOIN restaurant r 
        ON od.restaurant_id = r.restaurant_id
    GROUP BY r.restaurant_id, r.restaurant_name, c.customer_id, c.customer_name
) ranked
WHERE rn = 1;

# 11. Calculate the total number of orders placed on weekends. 
SELECT * FROM order_detail;

SELECT COUNT(*) AS total_weekend_orders
FROM order_detail
WHERE DAYOFWEEK(order_time) IN (1,7);

# 12. Calculate the average delivery time (in minutes) for orders placed on weekdays versus weekends. 
SELECT * FROM order_detail;

SELECT 
    CASE 
        WHEN DAYOFWEEK(order_time) IN (1,7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    AVG(TIMESTAMPDIFF(MINUTE, order_time, delivered_time)) AS avg_delivery_time_minutes
FROM order_detail
GROUP BY day_type;

# 13. List the top 5 most expensive food items. Display food_id, food_name, and price_per_unit for all food items with the highest 5 prices. 
SELECT * FROM foods;

SELECT food_id, food_name, price_per_unit
FROM 
(
  SELECT food_id, food_name, price_per_unit,
  DENSE_RANK() OVER (ORDER BY price_per_unit DESC) AS `rnk` 
  FROM foods
)food_ranked
WHERE rnk <= 5;

# 14. Find the restaurant with the most diverse menu (i.e., the highest number of food items). 
SELECT * FROM order_food;

SELECT restaurant_id, COUNT(DISTINCT food_id) AS total_items
FROM order_food
GROUP BY restaurant_id
ORDER BY total_items DESC
LIMIT 1;

# 15. Calculate total payment amount for each payment type.
SELECT * FROM payment_table;
SELECT * FROM foods;
SELECT * FROM order_detail;
SELECT * FROM order_food;

SELECT 
    p.payment_type,
    SUM(f.price_per_unit * ofd.quantity) AS total_payment_amount
FROM payment_table p
JOIN order_detail od 
    ON p.order_id = od.order_id
JOIN order_food ofd 
    ON od.order_id = ofd.order_id
JOIN foods f 
    ON ofd.food_id = f.food_id
GROUP BY p.payment_type;


